### ISSUE TITLE
Render FlowComponents into layout

### ISSUE THREAD

**Issue by gibson** [kadirahq/blaze-layout#23]
When i use 
```
FlowLayout.render 'main_layout',
        content: 'settings'
```
and i have a component `settings` -> rendering only Blaze.Template and not starting component

**Comment by arunoda** [comment]
I'm quite not sure what you are raising?
Could you work on a sample repo with isolated example.
So, we can fix it quickly.

**Comment by gibson** [comment]
https://github.com/gibson/flowtest

**Comment by lassombra** [comment]
Just curious, have you tried: 
{{> render component=content}}
instead of 
{{> Template.dynamic template=content}}

Template.dynamic is Blaze's provision for dynamically selecting a template.  render is Component's provision for rendering a component.

**Comment by arunoda** [comment]
I think @lassombra answer is correct.

**Comment by lassombra** [comment]
I threw together a quick and dirty proof of this working: http://meteorpad.com/pad/33RKCXvTrqqWME2HH/Flow-Component-In-Layout

You'll see there the Template.dynamic replaced with render.
