### ISSUE TITLE
jQuery Dependency -- $ is not a function

### ISSUE THREAD

**Issue by brunolemos** [kadirahq/blaze-layout#43]
Blaze Layout seems to be dependent of jQuery public symbol $, but it's not adding it automatically.
More specifically, the BlazeLayout.setRoot method.

If I remove the jquery package, this error appears:
    Exception in defer callback: TypeError: $ is not a function 

I don't believe jquery needs to be a dependency so it would be nice to not use it! 
Or, if it must be used,  it should be in the package dependencies to install it automatically, right? 

Thanks :)

**Comment by arunoda** [comment]
You are correct. Let's see what we do about it.

**Comment by arunoda** [comment]
Released a new version with depending on jQuery. We need to jquery since we allow to pass CSS selectors in `.setRoot()`.
Anyway, right now we need jQuery for blaze. So we need this.

**Comment by brunolemos** [comment]
Ok!
